DELETE http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imlsb2xhLm5pY29sYXVAZ21haWwuY29tIiwiaXNzIjoiZXZlbnQtYmFja2VuZC1hcGkiLCJzdWIiOiIxIiwiZXhwIjoxNzY3MTc5MjMzLCJpYXQiOjE3NjcxNzIwMzN9.NHUXl85K4WBUTB_0l_UO8mO7HTmjiGh3yfSjYf30_UY